
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_MOVIE_BYID = 'FETCH_MOVIE_BYID';
export const FETCH_MOVIE_BYID_SUCCESS = 'FETCH_MOVIE_BYID_SUCCESS';
export const FETCH_MOVIE_BYID_FAILURE = 'FETCH_MOVIE_BYID_FAILURE';

